### ISSUE TITLE
Tutorial Feature in the UI

### ISSUE THREAD

**Issue by ChengSashankh** [bucketlist-3216/bucketlist#102]
- Any functional method will do

**Comment by tanyonghe** [comment]
Implemented in PR #117 as a small demo; definitely need better screenshot images (my Adobe XD has some issues so I can't get it from there) and I'm not sure how it should appear during the user flow.
1. Where/when should the tutorial pop up?
2. Should we automatically redirect them or add in an additional button specifically for tutorial if the user has zero created trips so far?

**Comment by tanyonghe** [comment]
Implemented in PR #120
