### ISSUE TITLE
Handle error gracefully

### ISSUE THREAD

**Issue by karenfrilya97** [bucketlist-3216/bucketlist#178]
- [x] - Print predetermined error message e.g. "Sorry, something went wrong!" instead of e.g. "Request failed with status code 500"

Instead of `alert` with loading page in the background:
- [x]    - Use `toast` (if the error still allows redirection) or 
- [ ]    - Show an error page (if the error prevents the page from being shown in the background)

**Comment by ChengSashankh** [comment]
All completed except error page in #199
